spring:
  sleuth:
    sampler:
      probability: 1.0
    baggage:
      local-fields:        - event-custom-header
      remote-fields:
        - http-custom-header
      correlation-fields:
        - http-custom-header
        - event-custom-header
